In [2]:
import numpy as np
import pandas as pd
from itertools import combinations

In [3]:
filename = "../data/test_data.txt"
data = np.genfromtxt(filename, delimiter=',')
print(data)

[16. 10. 15.  5.  1. 11.  7. 19.  6. 12.  4.]


In [4]:
result_array=[0]
diff_array = []
last_val=0
data = np.sort(data)

while len(result_array) < len(data):
#     print(len(result_array))
    for i in enumerate(data):
#         print(last_val)
#         print
        diff = i[1] - last_val
#         print(diff)
        if diff == 1:
#             print("loop1")
            last_val = i[1]
            result_array.append(last_val)
            diff_array.append(diff)
            pass
        else:
            if diff == 2:
#                 print("loop2")
                last_val = i[1]
                result_array.append(last_val)
                diff_array.append(diff)
                pass
            else:
                if diff == 3:
#                     print("loop3")
                    last_val = i[1]
                    result_array.append(last_val)
                    diff_array.append(diff)
                    pass
                else:
                    pass
                        
result_array.append(last_val+3)
diff_array.append(3.0)


# b,c = np.unique(diff_array,return_counts=True)
# print(result_array)
# print(diff_array)
# print("1 counts:", c[1])
# print("3 counts:", c[2])
# product = c[1] * (c[2])
# print(product)

In [5]:
result = np.where(np.asarray(diff_array)==1.0)
print("Elements with value 1 exists at following indices", result[0], sep='\n')
print(result[0][-1])

Elements with value 1 exists at following indices
[0 2 3 4 6 7 9]
9


In [16]:
index=0
j=0
count=0
count_array = [0]
test_val = result_array[-1]
last_val=0
# data=np.asarray(data)
while index<result[0][-1]:
    if count_array[-1]==test_val:
        count=count+1
    print("count:",count)
    index = result[0][j]
    j+=1
    count_array=[0]
    last_val=0
    new_data = np.delete(data,index)
    print(new_data)
    while last_val != new_data[-1]:
#         print(len(count_array))
        for i in enumerate(new_data):
#             print(last_val)
#             print(i[1])
            diff = i[1] - last_val
            print(diff)
            if diff == 1:
                print("loop1")
                last_val = i[1]
                count_array.append(last_val)
                diff_array.append(diff)
                pass
            else:
                if diff == 2:
                    print("loop2")
                    last_val = i[1]
                    count_array.append(last_val)
                    diff_array.append(diff)
                    pass
                else:
                    if diff == 3:
                        print("loop3")
                        last_val = i[1]
                        count_array.append(last_val)
                        diff_array.append(diff)
                        pass
            break
        break
print(count)

count: 0
[ 4.  5.  6.  7. 10. 11. 12. 15. 16. 19.]
4.0
count: 0
[ 1.  4.  6.  7. 10. 11. 12. 15. 16. 19.]
1.0
loop1
count: 0
[ 1.  4.  5.  7. 10. 11. 12. 15. 16. 19.]
1.0
loop1
count: 0
[ 1.  4.  5.  6. 10. 11. 12. 15. 16. 19.]
1.0
loop1
count: 0
[ 1.  4.  5.  6.  7. 10. 12. 15. 16. 19.]
1.0
loop1
count: 0
[ 1.  4.  5.  6.  7. 10. 11. 15. 16. 19.]
1.0
loop1
count: 0
[ 1.  4.  5.  6.  7. 10. 11. 12. 15. 19.]
1.0
loop1
0


### 