In [3]:
import math
import numpy as np
import pandas as pd

In [108]:
filename = "../data/test_data.txt"
my_data = np.genfromtxt(filename, delimiter=',')
# df = pd.read_csv(filename,header=None,names=["data"])
# print(df)
print(my_data[0:25])

[ 35.  20.  15.  25.  47.  40.  62.  55.  65.  95. 102. 117. 150. 182.
 127. 219. 299. 277. 309. 576.]


In [110]:
def combination_test(pream,flag,test_val,pream_count):
    for preamble_iter1 in pream:
#         print(preamble_iter1)
#         print(len(pream))
        for preamble_iter2 in pream:
#             print(preamble_iter2)
            if preamble_iter2 == preamble_iter1:
#                 print("element1 : {},element2: {}, No sum".format(preamble_iter1,preamble_iter2))
                pass
            else:
                element_sum = preamble_iter1 + preamble_iter2
#                 print("element1 : {},element2 : {}, test value: {}, sum : {}".format(preamble_iter1,preamble_iter2,test_val,element_sum))
                if test_val==element_sum:
                    flag=1
    if preamble_iter1 == pream[pream_count-1] and flag==0:
        flagged_val=test_val
#         print("here1")   
    else:
        flagged_val=0
#         print("here2")   
    return(flag,flagged_val)


preamble_count = 5

# for i in enumerate(my_data):
#     preamble = my_data[i[0]:i[0]+preamble_count]
# #     print(preamble)
#     test_val = my_data[i[0]+preamble_count+1]
# #     print("new loop")
#     flag=0
#     for j in preamble:
# #         print(j)
# #         print(len(preamble))
#         for k in preamble:
# #             print(k)
#             if k==j:
# #                 print("element1 : {},element2: {}, No sum".format(k,j))
#                 pass
#             else:
#                 p=j+k
# #                 print("element1 : {},element2 : {}, test value: {}, sum : {}".format(k,j,test_val,p))
#                 if test_val==p:
#                     flag=1
# #                     print(flag)
#     if j == preamble[preamble_count-1] and flag==0:
#         print(test_val)

for i in enumerate(my_data):
    preamble = my_data[i[0]:i[0]+preamble_count]
    print(preamble)
    test_val = my_data[i[0]+preamble_count+1]
#     print("new loop")
    flag=0
    flag,value=combination_test(preamble,flag,test_val,preamble_count)
    if not value==0:
        print(value)

[35. 20. 15. 25. 47.]
[20. 15. 25. 47. 40.]
[15. 25. 47. 40. 62.]
[25. 47. 40. 62. 55.]
[47. 40. 62. 55. 65.]
[40. 62. 55. 65. 95.]
[ 62.  55.  65.  95. 102.]
[ 55.  65.  95. 102. 117.]
[ 65.  95. 102. 117. 150.]
127.0
[ 95. 102. 117. 150. 182.]
[102. 117. 150. 182. 127.]
[117. 150. 182. 127. 219.]
[150. 182. 127. 219. 299.]
[182. 127. 219. 299. 277.]
[127. 219. 299. 277. 309.]


IndexError: index 20 is out of bounds for axis 0 with size 20